CSUB-145 Skim events
gluwa/credal-js pull request #53
Opened 2022-05-04 18:44 UTC by CAGS295

2022-05-04 18:47 UTC, jfrank-summit commented on src/extrinsics/common.ts
> +    const transformWrapper = (dataItem: Codec, transform_fn: (data: SourceType) => ItemType) => {
```suggestion
    const transformWrapper = (dataItem: Codec, transformFn: (data: SourceType) => ItemType) => {
```

or something like that. Gotta use camelCase with javaScript.

2022-05-04 19:22 UTC, jfrank-summit requested changes
Cosmetic nitpicks. I like the approach!

2022-05-04 19:22 UTC, 0xjeremyfrank commented on src/extrinsics/common.ts
> +    if (codecItem != null) {
```suggestion
    if (codecItem) {
```
or you could use a ternary:
```
return codecItem ? { itemId, item:transformWrapper(codecItem, transform)} : {itemId}
```

2022-05-04 19:22 UTC, 0xjeremyfrank commented on src/model.ts
> +export type EventReturnType<I, D> = EventReturnIdType<I> | EventReturnJoinType<I, D>;
```suggestion
export type EventReturnType<Id, Data> = EventReturnIdType<Id> | EventReturnJoinType<Id, Data>;
```
for consistency

2022-05-04 19:22 UTC, jfrank-summit commented on src/model.ts
> +type EventReturnDataType<DataType> = {
Change generic to `Data` for consistency.

2022-05-05 11:06 UTC, jfrank-summit approved these changes
looks good

2022-05-05 12:04 UTC, atodorov approved these changes

2022-05-05 12:04 UTC, merged